### ISSUE TITLE
List of user's favorite markets

### ISSUE THREAD

**Issue by Coreyander** [CodePath-AND102-Group-12/FindingFresh#6]

**Comment by heynicortiz** [comment]
I've got a basis laid for this now. The layout is just a basic TextView that needs to be expanded on, but I iterated through the user and their collection of favorites (these are all just market name strings not document IDs right now so that could be improved on but it's working as is). Then create Markets based on querying Firestore for that list of favorites.

Just needs some RecyclerView/adapter work at the moment but at least we've got a plain text list working

**Comment by heynicortiz** [comment]
I've got the RecyclerView setup now as well, but there's some weird interaction going on between the RecyclerView and the temporary TextView I had implemented. If the TextView and related StringBuilder are removed, the RecyclerView doesn't show...hopefully one of you can figure that one out but for now I've just truncated it to the first characters and made it invisible...
